# Generated by Django 3.2 on 2023-09-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderproducts',
            name='product_status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('processing', 'Processsing'), ('delivered', 'Delivered')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('disabled', 'Disabled'), ('in review', 'In review')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_status',
            field=models.CharField(choices=[('published', 'Published'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('disabled', 'Disabled'), ('in review', 'In review')], default='in_review', max_length=10),
        ),
    ]
